# services:
#   - type: web
#     name: emotion-language-app
#     env: python
#     buildCommand: pip install -r requirements.txt
#     startCommand: gunicorn app:app
#     plan: free
#     envVars:
#       - key: PORT
#         value: 10000
        
services:
  - type: web
    name: detection-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # change this to match your actual entry point
    pythonVersion: 3.10.13
